//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Equipment
{
	public virtual Int Agility
	{
		get;
		set;
	}

	public virtual URL Image
	{
		get;
		set;
	}

	public virtual Int Gold
	{
		get;
		set;
	}

	public virtual Int Intelligence
	{
		get;
		set;
	}

	public virtual Int Strength
	{
		get;
		set;
	}

	public virtual object Name
	{
		get;
		set;
	}

}

