//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ninja.domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ninja
    {
        public Ninja()
        {
            this.Equipment = new HashSet<Equipment>();
        }
    
        public string Name { get; set; }
        public int Agility { get; set; }
        public int Intelligence { get; set; }
        public int Strength { get; set; }
        public int Gold { get; set; }
    
        public virtual ICollection<Equipment> Equipment { get; set; }
    }
}
