//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Equipment
{
	public virtual int Agility
	{
		get;
		set;
	}

	public virtual string Image
	{
		get;
		set;
	}

	public virtual int Gold
	{
		get;
		set;
	}

	public virtual int Intelligence
	{
		get;
		set;
	}

	public virtual int Strength
	{
		get;
		set;
	}

	public virtual object Name
	{
		get;
		set;
	}

}

