//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Ninja
{
	public virtual Head currentHead
	{
		get;
		set;
	}

	public virtual Shoulder currentShoulder
	{
		get;
		set;
	}

	public virtual Chest currentChest
	{
		get;
		set;
	}

	public virtual Legs currentLegs
	{
		get;
		set;
	}

	public virtual Boots currentBoots
	{
		get;
		set;
	}

	public virtual int Strength
	{
		get;
		set;
	}

	public virtual int Intelligence
	{
		get;
		set;
	}

	public virtual int Agility
	{
		get;
		set;
	}

	public virtual int Gold
	{
		get;
		set;
	}

	public virtual string NinjaImg
	{
		get;
		set;
	}

	public virtual Equipment Equipment
	{
		get;
		set;
	}

	public virtual Store Store
	{
		get;
		set;
	}

}

