//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Store
{
	public virtual Int Gold
	{
		get;
		set;
	}

	public virtual Dictionary<String,List > EquipmentCollection
	{
		get;
		set;
	}

	public virtual Equipment Equipment
	{
		get;
		set;
	}

}

